[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "event-platform"
type = "web"
port = 3000

[services.env]
NODE_ENV = "production"
NIXPACKS_BUILD_CMD = "npm run build"
NIXPACKS_START_CMD = "npm run start"
